// Ba danh sách sự kiện app (plan §0, §2.2). Thứ tự trong danh sách = thứ tự hiển thị.
//
// - vnHolidays: ngày nghỉ lễ chính thức theo Bộ luật Lao động 2019, Điều 112.
//   Ngày nghỉ thêm/hoán đổi theo năm (30 Tết, mùng 4–5, ngày thứ 2 của Quốc khánh,
//   nghỉ bù) KHÔNG nằm ở đây mà qua YearOverride (Sheet → §2.3).
// - vnMemorials: ĐỀ XUẤT của agent (D019), user duyệt/sửa; không ảnh hưởng ngày nghỉ.
// - international: đúng danh sách plan §2.2; "Năm mới 1/1" gộp vào Tết Dương lịch
//   (vnHolidays) để không hiện 2 dòng cùng ngày (D019).
import 'event.dart';

/// Lễ VN nghỉ chính thức (ngày cố định).
const List<Event> vnHolidays = [
  Event(
    id: 'tet-duong-lich',
    title: 'Tết Dương lịch',
    kind: EventKind.vnHoliday,
    type: CalendarType.solar,
    month: 1,
    day: 1,
    description: 'Năm mới',
  ),
  Event(
    id: 'tet',
    title: 'Tết Nguyên đán',
    kind: EventKind.vnHoliday,
    type: CalendarType.lunar,
    month: 1,
    day: 1,
    durationDays: 3,
    description: 'Mùng 1–3; ngày 30 Tết và nghỉ thêm theo lịch nghỉ từng năm',
  ),
  Event(
    id: 'gio-to',
    title: 'Giỗ Tổ Hùng Vương',
    kind: EventKind.vnHoliday,
    type: CalendarType.lunar,
    month: 3,
    day: 10,
  ),
  Event(
    id: 'giai-phong',
    title: 'Ngày Giải phóng miền Nam',
    kind: EventKind.vnHoliday,
    type: CalendarType.solar,
    month: 4,
    day: 30,
  ),
  Event(
    id: 'quoc-te-lao-dong',
    title: 'Ngày Quốc tế Lao động',
    kind: EventKind.vnHoliday,
    type: CalendarType.solar,
    month: 5,
    day: 1,
  ),
  Event(
    id: 'quoc-khanh',
    title: 'Ngày Quốc khánh',
    kind: EventKind.vnHoliday,
    type: CalendarType.solar,
    month: 9,
    day: 2,
    description: 'Ngày nghỉ thứ 2 (1/9 hoặc 3/9) theo lịch nghỉ từng năm',
  ),
];

/// Lễ / kỷ niệm VN, không nghỉ (đề xuất, D019).
const List<Event> vnMemorials = [
  // Dương
  Event(
    id: 'thanh-lap-dang',
    title: 'Ngày thành lập Đảng Cộng sản Việt Nam',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 2,
    day: 3,
  ),
  Event(
    id: 'thay-thuoc',
    title: 'Ngày Thầy thuốc Việt Nam',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 2,
    day: 27,
  ),
  Event(
    id: 'quoc-te-phu-nu',
    title: 'Ngày Quốc tế Phụ nữ',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 3,
    day: 8,
  ),
  Event(
    id: 'thanh-lap-doan',
    title: 'Ngày thành lập Đoàn TNCS Hồ Chí Minh',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 3,
    day: 26,
  ),
  Event(
    id: 'dien-bien-phu',
    title: 'Chiến thắng Điện Biên Phủ',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 5,
    day: 7,
  ),
  Event(
    id: 'sinh-nhat-bac',
    title: 'Ngày sinh Chủ tịch Hồ Chí Minh',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 5,
    day: 19,
  ),
  Event(
    id: 'bao-chi',
    title: 'Ngày Báo chí Cách mạng Việt Nam',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 6,
    day: 21,
  ),
  Event(
    id: 'gia-dinh',
    title: 'Ngày Gia đình Việt Nam',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 6,
    day: 28,
  ),
  Event(
    id: 'thuong-binh-liet-si',
    title: 'Ngày Thương binh Liệt sĩ',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 7,
    day: 27,
  ),
  Event(
    id: 'cach-mang-thang-tam',
    title: 'Ngày Cách mạng tháng Tám thành công',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 8,
    day: 19,
  ),
  Event(
    id: 'giai-phong-thu-do',
    title: 'Ngày Giải phóng Thủ đô',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 10,
    day: 10,
  ),
  Event(
    id: 'doanh-nhan',
    title: 'Ngày Doanh nhân Việt Nam',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 10,
    day: 13,
  ),
  Event(
    id: 'phu-nu-viet-nam',
    title: 'Ngày Phụ nữ Việt Nam',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 10,
    day: 20,
  ),
  Event(
    id: 'nha-giao',
    title: 'Ngày Nhà giáo Việt Nam',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 11,
    day: 20,
  ),
  Event(
    id: 'quan-doi',
    title: 'Ngày thành lập Quân đội nhân dân Việt Nam',
    kind: EventKind.vnMemorial,
    type: CalendarType.solar,
    month: 12,
    day: 22,
  ),
  // Âm
  Event(
    id: 'ram-thang-gieng',
    title: 'Rằm tháng Giêng (Tết Nguyên tiêu)',
    kind: EventKind.vnMemorial,
    type: CalendarType.lunar,
    month: 1,
    day: 15,
  ),
  Event(
    id: 'han-thuc',
    title: 'Tết Hàn thực',
    kind: EventKind.vnMemorial,
    type: CalendarType.lunar,
    month: 3,
    day: 3,
  ),
  Event(
    id: 'phat-dan',
    title: 'Lễ Phật Đản',
    kind: EventKind.vnMemorial,
    type: CalendarType.lunar,
    month: 4,
    day: 15,
  ),
  Event(
    id: 'doan-ngo',
    title: 'Tết Đoan Ngọ',
    kind: EventKind.vnMemorial,
    type: CalendarType.lunar,
    month: 5,
    day: 5,
  ),
  Event(
    id: 'vu-lan',
    title: 'Lễ Vu Lan (Rằm tháng Bảy)',
    kind: EventKind.vnMemorial,
    type: CalendarType.lunar,
    month: 7,
    day: 15,
  ),
  Event(
    id: 'trung-thu',
    title: 'Tết Trung Thu',
    kind: EventKind.vnMemorial,
    type: CalendarType.lunar,
    month: 8,
    day: 15,
  ),
  Event(
    id: 'ong-tao',
    title: 'Ông Công Ông Táo',
    kind: EventKind.vnMemorial,
    type: CalendarType.lunar,
    month: 12,
    day: 23,
  ),
];

/// Ngày quốc tế (plan §2.2; Năm mới 1/1 nằm ở [vnHolidays]).
const List<Event> international = [
  Event(
    id: 'valentine',
    title: 'Lễ tình nhân (Valentine)',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 2,
    day: 14,
  ),
  Event(
    id: 'ca-thang-tu',
    title: 'Ngày Cá tháng Tư',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 4,
    day: 1,
  ),
  Event(
    id: 'trai-dat',
    title: 'Ngày Trái Đất',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 4,
    day: 22,
  ),
  Event(
    id: 'ngay-cua-me',
    title: 'Ngày của Mẹ',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 5,
    nthWeekday: NthWeekday(weekday: DateTime.sunday, n: 2),
    description: 'Chủ nhật thứ 2 của tháng 5',
  ),
  Event(
    id: 'quoc-te-thieu-nhi',
    title: 'Ngày Quốc tế Thiếu nhi',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 6,
    day: 1,
  ),
  Event(
    id: 'ngay-cua-cha',
    title: 'Ngày của Cha',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 6,
    nthWeekday: NthWeekday(weekday: DateTime.sunday, n: 3),
    description: 'Chủ nhật thứ 3 của tháng 6',
  ),
  Event(
    id: 'nha-giao-quoc-te',
    title: 'Ngày Nhà giáo Quốc tế',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 10,
    day: 5,
  ),
  Event(
    id: 'halloween',
    title: 'Halloween',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 10,
    day: 31,
  ),
  Event(
    id: 'giang-sinh',
    title: 'Lễ Giáng sinh',
    kind: EventKind.international,
    type: CalendarType.solar,
    month: 12,
    day: 25,
  ),
];

/// Toàn bộ sự kiện app theo thứ tự nhóm: nghỉ → kỷ niệm → quốc tế.
const List<Event> allEvents = [...vnHolidays, ...vnMemorials, ...international];
